#!/bin/bash

#Функция 1
    function script1() {
#1 Открыть CLI Transformers 
    bash <(curl -s https://raw.githubusercontent.com/unonodes/projects/main/transformers/tfsc_open.sh)
    echo "Выполнен скрипт 1"
}

#Функция 2
     function script2() {
#2 Закрыть CLI и запустить servise_file Transformers
     bash <(curl -s https://raw.githubusercontent.com/unonodes/projects/main/transformers/start_tfsc.service)
     echo "Выполнен скрипт 2"
}

#Функция 3
    function script3() {
#3 Проверка запущенных сессий Tmux
    echo "Запущенные оболочки Tmux"
    echo "------------------------"
    echo " $(tmux ls) "
    echo "------------------------"
}

#Функция 4
    function script4() {
#4 Проверка статуса службы tfsc.service
    echo "Статуса службы tfsc.service"
    echo "------------------------"
    echo " $(sudo systemctl status tfsc.service) "
    echo "------------------------"
}

#Функция 99
    function script99() {
#1 Вернуться к списку NOD 
    bash <(curl -s https://raw.githubusercontent.com/unonodes/projects/main/list)
    echo "Выполнен скрипт 99"
}


# функция для вывода меню
function menu() {
    clear
    echo "Меню:"
    echo "1. Открыть CLI Transformers"
    echo "2. Закрыть CLI и запустить servise_file Transformers"
    echo " "
    echo "Дополнительные функции:"
    echo "3. Проверка запущенных сессий Tmux"
    echo "4. Проверка статуса службы tfsc.service"
    echo "9. Выйти"
    echo "99. Список nodes"
}

# цикл вывода меню и обработки ввода пользователя
while true
do
    menu
    read -p "Выберите опцию: " option
    case $option in
        1)
            script1
            read -p "Нажмите ENTER для продолжения..."
            ;;
        2)
            script2
            read -p "Нажмите ENTER для продолжения..."
            ;;
        3)
            script3
            read -p "Нажмите ENTER для продолжения..."
            ;; 
        4)
            script4
            read -p "Нажмите ENTER для продолжения..."
            ;; 
        9)
            exit 0
            ;;
        99)
            script99
            read -p "Нажмите ENTER для продолжения..."
            ;;  
        *)
            echo "Неверная опция. Попробуйте еще раз."
            read -p "Нажмите ENTER для продолжения..."
            ;;
    esac
done
